apiVersion: v1
kind: Deployment
services:
  backend:
    image: ghcr.io/sorensenelena/simple-fortune-cookie-backend:latest
    ports:
      - "9000:9000"
    restart: unless-stopped

  frontend:
    image: ghcr.io/sorensenelena/simple-fortune-cookie-frontend:latest
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: unless-stopped
